<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-06 17:54

$extensionPath = t3lib_extMgm::extPath('pnf_gallery_video');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_pnfgalleryvideo_dam' => $extensionClassesPath . 'class.tx_pnfgalleryvideo_dam.php',
	'tx_pnfgalleryvideo_renderfile' => $extensionClassesPath . 'class.tx_pnfgalleryvideo_renderfile.php',
	'tx_pnfgalleryvideo_singlevideo' => $extensionPath . 'themes/singlevideo/class.tx_pnfgalleryvideo_singlevideo.php',
	'tx_pnfgalleryvideo_userfunc' => $extensionClassesPath . 'class.tx_pnfgalleryvideo_userfunc.php',
);
?>