<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-08-23 16:10

$extensionPath = t3lib_extMgm::extPath('pnf_gallery_share');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_pnfgalleryshare_markers' => $extensionClassesPath . 'class.tx_pnfgalleryshare_markers.php',
);
?>